---
# 二、K8S集群容器运行时 Containerd准备

# 2.1 Containerd部署文件获取
- name: Download containerd
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.7.5/cri-containerd-1.7.5-linux-amd64.tar.gz
    dest: /tmp/cri-containerd-1.7.5-linux-amd64.tar.gz

- name: Extract containerd
  unarchive:
    src: /tmp/cri-containerd-1.7.5-linux-amd64.tar.gz
    dest: /
    remote_src: yes

# 2.2 Containerd配置文件生成并修改
- name: Create containerd configuration directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd configuration
  command: containerd config default
  register: containerd_config
  args:
    creates: /etc/containerd/config.toml

- name: Modify containerd configuration
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^sandbox_image = .+', line: 'sandbox_image = "registry.k8s.io/pause:3.9"' }
    - { regexp: '^SystemdCgroup = .+', line: 'SystemdCgroup = true' }

# 2.3 Containerd启动及开机自启动
- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started

# 三、K8S集群部署

# 3.1 K8S集群软件apt源准备
- name: Add Kubernetes apt key
  apt_key:
    url: https://mirrors.aliyun.com/kubernetes-new/core/stable/v1.29/deb/Release.key
    state: present

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb https://mirrors.aliyun.com/kubernetes-new/core/stable/v1.29/deb/ /"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

# 3.2 K8S集群软件安装
- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    mark: hold

# 3.4 Worker 节点加入集群
- name: Join worker node to cluster
  command: /root/kubeadm_join_command.sh
  when: join_command is defined
